# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.1.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  create-app:
    macos:
      xcode: 13.1.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: create_app
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-test-app:
    jobs:
      - build-and-test
      - create-app:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
